services:
  - type: web
    name: chronora-flutter-dev
    runtime: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeployTrigger: commit
